### ISSUE TITLE
Criar arquivo .gitignore

### ISSUE THREAD

**Issue by manoelcampos** [trasherdave/retorno-boleto-funcional#1]
Só uma dica. Todo projeto normalmente deve ter um arquivo `.gitignore` na raiz, para dizer que tipos de arquivos não devem ser incluídos no repositório git. Isto inclui arquivos compilados.

Como tais arquivos são gerados a partir do build do projeto, eles são totalmente desnecessários e só aumentam o tamanho do repositório e tempo de download. Adicionalmente, se for trabalhar em equipe, isso vai causar conflitos pois os arquivos compilados são alterados o tempo todo por diferentes devs a cada compilação.

Em projeto maven, basta incluir a linha abaixo no arquivo para ignorar a pasta target inteira, contendo os compilados:

```
target/
```

Para remover a pasta target do seu repo, basta fazer: 

```bash
git rm -rf retorno-boleto-funcional/target/
git add .
git commit -m "Remove pasta target de arquivos compilados"
git push
```

**Comment by trasherdave** [comment]
Ótima dica! Obrigado!
